### ISSUE TITLE
[PE-D] Value of expense can be negative for add command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-2/tp#199]
Value of expense is allowed to be negative when it should be an absolute value:

![image.png](https://raw.githubusercontent.com/aaapppsss/ped/main/files/ff13d1e8-62ab-48cc-9ed9-8904b432cc57.png)

Expected to throw an error.

Result when viewing total expenses:

![image.png](https://raw.githubusercontent.com/aaapppsss/ped/main/files/501c998e-f4c0-41eb-983e-cc45c513745b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: aaapppsss/ped#1

**Comment by pos0414** [comment]
Fixed by disabling negative amount as user input.
