### ISSUE TITLE
[PE-D] Add recurring entries command allows value for income to be negative 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-2/tp#222]
Add recurring entries command allows value of income to be negative when it should be an absolute value

![image.png](https://raw.githubusercontent.com/aaapppsss/ped/main/files/dd7520f9-f174-4cb5-9ee2-7edc5987844c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: aaapppsss/ped#10

**Comment by pos0414** [comment]
Fixed by disabling user to input negative amounts.
