### ISSUE TITLE
[PE-D] There is no information showing how to edit records

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-2/tp#223]
![PE-4.jpg](https://raw.githubusercontent.com/oneScotch/ped/main/files/0fb2dc0e-3af3-4712-9213-4c87e92314f9.jpg)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: oneScotch/ped#5

**Comment by irvinseet** [comment]
@Yitching  perhaps we can update the message to be clearer. 
"what would you like to edit? type the tag and what you want to change e.g. a/10"
