### ISSUE TITLE
[PE-D] Budget Command: Incorrectly counts negative expenses

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W11-2/tp#224]
Technically, it should be `-$199.00 / Not set`?

![image.png](https://raw.githubusercontent.com/kahhe/ped/main/files/6bb94a19-ece5-4232-b8c9-9f29c650568b.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kahhe/ped#12

**Comment by pos0414** [comment]
Fixed by disabling user to input negative amounts.
